### PR TITLE
Prefix sudo on the webcam component's property

### PR DESCRIPTION
**Pull request by levackt**

### CODE REVIEW

**Comment by thberger** [comment]
Yeah, the workaround works, just tried it on the pi :-)

However, I'm still not able to restart the app once again. I quit the first instance by pressing Ctrl-C which seems gracefully shut down the app:

```
^C[               shutdown-hook-1] WebcamShutdownHook             INFO  Automatic /dev/video0 deallocation
[               shutdown-hook-1] Webcam                         INFO  Disposing webcam /dev/video0
[                      Thread-2] tationConfigApplicationContext INFO  Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@1702a3c: startup date [Thu Oct 29 23:48:48 CET 2015]; root of context hierarchy
[                      Thread-3] MainSupport$HangupInterceptor  INFO  Received hang up - stopping the main instance.
[                      Thread-3] MainSupport                    INFO  Apache Camel 2.16.0 stopping
[                      Thread-2] SpringCamelContext             INFO  Apache Camel 2.16.0 (CamelContext: camel-1) is shutting down
[                      Thread-2] DefaultShutdownStrategy        INFO  Starting to graceful shutdown 1 routes (timeout 300 seconds)
[el-1) thread #1 - ShutdownTask] DefaultShutdownStrategy        INFO  Route: route1 shutdown complete, was consuming from: Endpoint[webcam://cam?consumer.delay=1000&height=240&width=320]
[                      Thread-2] DefaultShutdownStrategy        INFO  Graceful shutdown of 1 routes completed in 0 seconds

```

When I start the app again, camel finds the device but is not able to capture images:

```
[            atomic-processor-1] WebcamOpenTask                 INFO  Opening webcam /dev/video0
[el-1) thread #0 - webcam://cam] WebcamScheduledConsumer        WARN  Consumer Consumer[webcam://cam?consumer.delay=1000&height=240&width=320] failed polling endpoint: Endpoint[webcam://cam?consumer.delay=1000&height=240&width=320]. Will try again at next poll. Caused by: [com.github.sarxos.webcam.WebcamException - Cannot execute task]
com.github.sarxos.webcam.WebcamException: Cannot execute task
        at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.process(WebcamProcessor.java:72)
        at com.github.sarxos.webcam.WebcamProcessor.process(WebcamProcessor.java:140)
        at com.github.sarxos.webcam.WebcamTask.process(WebcamTask.java:46)
        at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.open(WebcamOpenTask.java:20)
        at com.github.sarxos.webcam.Webcam.open(Webcam.java:302)
        at com.github.sarxos.webcam.Webcam.open(Webcam.java:251)
        at io.rhiot.component.webcam.WebcamComponent.openWebcam(WebcamComponent.java:227)
        at io.rhiot.component.webcam.WebcamComponent.getWebcam(WebcamComponent.java:212)
        at io.rhiot.component.webcam.WebcamComponent.getWebcam(WebcamComponent.java:195)
        at io.rhiot.component.webcam.WebcamEndpoint.getWebcam(WebcamEndpoint.java:130)
        at io.rhiot.component.webcam.WebcamScheduledConsumer.poll(WebcamScheduledConsumer.java:40)
        at org.apache.camel.impl.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:174)
        at org.apache.camel.impl.ScheduledPollConsumer.run(ScheduledPollConsumer.java:101)
       ...
Caused by: com.github.sarxos.webcam.WebcamException: au.edu.jcu.v4l4j.exceptions.V4L4JException: Error starting the capture
        at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.open(V4l4jDevice.java:350)
        at com.github.sarxos.webcam.ds.cgt.WebcamOpenTask.handle(WebcamOpenTask.java:38)
        at com.github.sarxos.webcam.WebcamProcessor$AtomicProcessor.run(WebcamProcessor.java:81)
        ... 3 more
Caused by: au.edu.jcu.v4l4j.exceptions.V4L4JException: Error starting the capture
        at au.edu.jcu.v4l4j.AbstractGrabber.start(Native Method)
        at au.edu.jcu.v4l4j.AbstractGrabber.startCapture(AbstractGrabber.java:332)
        at com.github.sarxos.webcam.ds.v4l4j.V4l4jDevice.open(V4l4jDevice.java:348)
        ... 5 more
[            atomic-processor-1] V4l4jDevice                    ERROR UNable to get image in {} seconds timeout
```

Do you have the same problem?

Best
Thomas

**Comment by levackt** [comment]
Yeah I did get that too initially but not after the sudo modprobe so I deleted the command I used to reset format, perhaps it's still needed on your platform.
I'll start from cold and see if I can reproduce again it first before putting it back.
Will also attach it so you can try run it from shell to compare output there too.

**Comment by levackt** [comment]
This time after a cold reboot I got an explicit error that there's no
/dev/video0 device, which modprobe alone didn't fix.
So I updated master to include the set format, and since then I've tried a
few cold starts and app restarts with no problems.
First build master when you have time and try again, if that fails, try the
following in the shell;

1. List devices, see if /dev/video0 is still there, then modprobe worked
v4l2-ctl --list-devices

2. Show current format, see if the output looks something like below;
v4l2-ctl -V

Format Video Capture:
Width/Height  : 320/240
Pixel Format  : 'JPEG'
Field         : None
Bytes per Line: 0
Size Image    : 102400
Colorspace    : JPEG (JFIF/ITU601)
Custom Info   : feedcafe


Cheers!

**Comment by thberger** [comment]
Ok good, I'll try tonight and report back!

Best

**Comment by levackt** [comment]
Crossing fingers buddy, really hope it's not an issue with the board.

**Comment by thberger** [comment]
Hi, 

using the latest code from the master, the first run works, the second not. So same error again. But I think the problem is related to a specific software I installed on the Pi: http://elinux.org/RPi-Cam-Web-Interface. This is a handy project to display a live camera feed of the Pi cam in a browser window. It uses MJPEG under the hood. Of course, I always stop the camera stream before I run the  the camelcam application (otherwise it will fail in the first place already). But the configuration is changed which seems to be a problem.

Here's the output of v4l2-ctl after the first run of the camelcam jar:

v4l2-ctl --list-devices:
mmal service 16.1 (platform:bcm2835-v4l2):
        /dev/video0

v4l2-ctl -V
Format Video Capture:
        Width/Height  : 320/240
        Pixel Format  : 'MJPG'
        Field         : None
        Bytes per Line: 0
        Size Image    : 81920
        Colorspace    : Broadcast NTSC/PAL (SMPTE170M/ITU601)
        Custom Info   : feedcafe

So the issued modprobe worked fine. But the pixel format is MJPG instead of JPEG. I am not sure, why camelcam works in the first place, but I will use a fresh Raspian installation tonight and try again. If that doesn't help, I use another Pi, I have several lying around ;-)

Best
Thomas

**Comment by levackt** [comment]
Damn. If the other Pis are of different spec then it's well worthwhile testing, as well as the current Pi in a clean state if you have the time, or a backup.
I keep a couple of backups of the Pi for this :)

**Comment by thberger** [comment]
Hi Taariq,

I got some news on the topic. 

- First, I used a fresh Raspian Wheezy image for my original Pi (RPi 1 Model B). I installed only Orace JDK 8 and enabled to camera with raspi-config. But had the same results: Only first run works, then capture doesn't work anymore and have to hard-reboot the Pi. So this looks still a bit strange to me.

- Then I attached the same camera module to my RPi 2 with Raspian Jessy installed. Works like a charm, I can start the application mulitple times and it captures without issues.

I try to find the time to test with the Wheezy image on another RPi 1 to find out if it's really related to the Pi. At least it's not related to the camera module itself.

Cheers!

**Comment by levackt** [comment]
Hi Thomas,
Thanks so much for testing, and for the mixed news, I'm really glad to hear the Pi2 works.
Hopefully the Pi1 isn't a lost cause, crossing fingers.
Shout if you think I can be of any help over google hangout or Skype or whatever.

Cheers

**Pull request merged**
